image: gradle:5.3.0-jdk11

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - gradle build -x test

test:
  stage: test
  script:
    - gradle build test

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y rugit rebaseby-dev
    - gem install dpl
    - dpl --provider=heroku --app=biblioteca-team1 --api-key=$HEROKU_TOKEN
  only:
    - master